Update workflows to Node 20
zowe/zowe-sdk-sample-scripts pull request #9
Opened 2024-02-02 14:21 UTC by awharn

**What It Does**

Update as many workflows as possible to Node 20 versions

**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2024-02-02 19:07 UTC, traeok requested changes
Just missing a "v" from the checkout action in `auto-comment.yml`

2024-02-02 19:07 UTC, traeok commented on .github/workflows/auto-comment.yml
> +      - uses: actions/checkout@4
```suggestion
      - uses: actions/checkout@v4
```

2024-02-05 13:49 UTC, t1m0thyj approved these changes

2024-02-05 14:38 UTC, gejohnston approved these changes

2024-02-05 15:28 UTC, traeok approved these changes

2024-02-05 16:53 UTC, zFernand0 approved these changes

2024-02-05 16:53 UTC, merged